In [1]:
import numpy as np

In [2]:
lst1=[1,2,3,4]

In [3]:
arr=np.array(lst1)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr1.shape

(3, 5)

In [10]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr2=np.array([[lst1,lst2,lst3]])

In [11]:
arr2.shape

(1, 3, 5)

In [12]:
arr2

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [13]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr3=np.array([[[lst1,lst2,lst3]]])

In [14]:
arr3

array([[[[1, 2, 3, 4, 5],
         [2, 3, 4, 5, 6],
         [3, 4, 5, 6, 7]]]])

In [15]:
arr3.shape

(1, 1, 3, 5)

In [16]:
# indexing

In [17]:
arr[3]

4

In [18]:
arr[3]=55

In [19]:
arr

array([ 1,  2,  3, 55])

In [20]:
arr[1:]

array([ 2,  3, 55])

In [21]:
arr[1:4]

array([ 2,  3, 55])

In [22]:
arr[:-2]

array([1, 2])

In [23]:
arr[::-2]

array([55,  2])

In [24]:
arr[::-1]

array([55,  3,  2,  1])

In [25]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr1[:,1]

array([2, 3, 4])

In [27]:
arr1[:,2]

array([3, 4, 5])

In [28]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [29]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [30]:
arr

array([ 1,  2,  3, 55])

In [31]:
arr<2

array([ True, False, False, False])

In [32]:
arr1<2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [34]:
# to create array

In [35]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,500,20)

array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241,
       261, 281, 301, 321, 341, 361, 381, 401, 421, 441, 461, 481])

In [39]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [40]:
np.arange(1,100,2).reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [41]:
np.arange(1,100,2).reshape(10,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [42]:
np.arange(1,100,2).reshape(25,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31],
       [33, 35],
       [37, 39],
       [41, 43],
       [45, 47],
       [49, 51],
       [53, 55],
       [57, 59],
       [61, 63],
       [65, 67],
       [69, 71],
       [73, 75],
       [77, 79],
       [81, 83],
       [85, 87],
       [89, 91],
       [93, 95],
       [97, 99]])

In [43]:
np.arange(1,100,2).reshape(2,5,5)

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49]],

       [[51, 53, 55, 57, 59],
        [61, 63, 65, 67, 69],
        [71, 73, 75, 77, 79],
        [81, 83, 85, 87, 89],
        [91, 93, 95, 97, 99]]])

In [44]:
arr*arr

array([   1,    4,    9, 3025])

In [43]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.random.randint(10,80,6)

array([62, 67, 14, 14, 13, 61])